### ISSUE TITLE
Add an example mixing FileLogger and FormatLogger ?

### ISSUE THREAD

**Issue by BambOoxX** [JuliaLogging/LoggingExtras.jl#48]
I just asked a question on the julia discource about this [here](https://discourse.julialang.org/t/combination-of-formatlogger-and-filelogger-in-loggingextras/60654), but this may be considered for a documentation improvement too, probably in the "More examples" section. Otherwise, this is very nice work.

**Comment by oxinabox** [comment]
I think you probably just want an example of using `FormatLogger` on a file?

That would indeed be a reasonable example.

It is just 
`FormatLogger(fmt, open("myfile.log", "w"))`

**Comment by fredrikekre** [comment]
It would be possible to define
```
function FormatLogger(f::Function, file::AbstractString; append=false, kwargs...)
    io = open(file, append ? "a" : "w")
    return FormatLogger(f, io; kwargs...)
end
```
but perhaps that puts "too much" functionality into the `FormatLogger`, and might be clearer to just open the file yourself.
