### ISSUE TITLE
Implement some log format functions in this package?

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLogging/LoggingExtras.jl#50]
`LoggingExtras` has two loggers that accept a function `(io, args) -> message` for formatting (`FormatLogger` and `DatetimeRotatingFileLogger`). In [`LokiLogger`](https://github.com/fredrikekre/LokiLogger.jl) I used the same interface. In that package I also provide two pre-defined format functions [`json`](https://github.com/fredrikekre/LokiLogger.jl/blob/8c94242fed55e8adc17ec9c54f79fefdc0e84119/src/LokiLogger.jl#L128-L133) for formatting the message as JSON, and [`logfmt`](https://github.com/fredrikekre/LokiLogger.jl/blob/8c94242fed55e8adc17ec9c54f79fefdc0e84119/src/LokiLogger.jl#L82-L88) for formatting as [`logfmt`](https://brandur.org/logfmt).

I feel like these type of pre-defined formatting function can be useful to others. I thought about either creating a separate `LoggingFormats` package, or to include it in this package. In addition to the ones I mentioned it could make sense to also (re)define the formatting from `ConsoleLogger` and `SimpleLogger` perhaps. Thoughts?

**Comment by racinmat** [comment]
I really like this idea, I have truncating logger in https://github.com/JuliaLogging/LoggingExtras.jl/pull/56, which I think would be useful too.

**Comment by fredrikekre** [comment]
https://github.com/JuliaLogging/LoggingFormats.jl
