### ISSUE TITLE
Logging local scope variables in custom logger?

### ISSUE THREAD

**Issue by zalmoxis** [JuliaLogging/LoggingExtras.jl#72]
Hi there,
I am not sure if this is an issue to open here but I think it is likely specifically related to this package. I posted the question here:
https://discourse.julialang.org/t/logger-local-variable-context/87828
https://stackoverflow.com/questions/73885345/how-can-i-access-local-scope-variables-in-julia-custom-loggers

Is this something I should turn into an issue here, or could we discuss this on discourse or SO?

**Comment by oxinabox** [comment]
This isn't possible to solve by a change in this package.
I will reply on Discourse
