### ISSUE TITLE
export withlevel

### ISSUE THREAD

**Issue by oxinabox** [JuliaLogging/LoggingExtras.jl#81]
I feel like since the Logging std lib exports `with_logger` 
we should export `withlevel`, possibly with the snakecase `with_level` to match
(and deprecate the old name)

**Comment by oxinabox** [comment]
@quinnj thoughts, since you introduced it.
Why wasn't it exported initially?

**Comment by quinnj** [comment]
I can't remember exactly other than just trying to be conservative at first to make sure it panned out and worked as expected. I'd be fine exporting and renaming.

**Comment by quinnj** [comment]
done in #94
