### ISSUE TITLE
Should `FileLogger` close the `io` stream somehow?

### ISSUE THREAD

**Issue by ericphanson** [JuliaLogging/LoggingExtras.jl#86]
https://github.com/JuliaLogging/LoggingExtras.jl/blob/d35e7c8cfc197853ee336ace17182e6ed36dca24/src/Sinks/filelogger.jl#L19-L20
Perhaps `atexit(() -> close(io))` would be appropriate?

I have not seen any bugs from the current implementation, but I do worry one could lose logs when `always_flush=false`.

**Comment by ericphanson** [comment]
Ah I guess that's https://github.com/JuliaLang/julia/blob/5dfaef7a67c9b58ed272ba8557bcad103bb814e3/base/iostream.jl#L28 or similar?

Probably another reason https://github.com/JuliaLang/julia/pull/51466 is dangerous then. But I guess it is safe for now, as long as we keep running finalizers on exit

**Comment by oxinabox** [comment]
the fear of losing logs when `always_flush` is false, is exactly why we provide the `always_flush` flag.
